{"uuid": "14783993-42e2-47c4-aa61-3133d4e5672b", "children": ["5478ca46-a444-4d66-930b-343f8864569f"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=116.0.5845.97)\nStacktrace:\n\tGetHandleVerifier [0x00D237C3+48947]\n\t(No symbol) [0x00CB8551]\n\t(No symbol) [0x00BBC92D]\n\t(No symbol) [0x00BA36E5]\n\t(No symbol) [0x00C08CDB]\n\t(No symbol) [0x00C17113]\n\t(No symbol) [0x00C04E86]\n\t(No symbol) [0x00BE16C7]\n\t(No symbol) [0x00BE284D]\n\tGetHandleVerifier [0x00F6FDF9+2458985]\n\tGetHandleVerifier [0x00FB744F+2751423]\n\tGetHandleVerifier [0x00FB1361+2726609]\n\tGetHandleVerifier [0x00DA0680+560624]\n\t(No symbol) [0x00CC238C]\n\t(No symbol) [0x00CBE268]\n\t(No symbol) [0x00CBE392]\n\t(No symbol) [0x00CB10B7]\n\tBaseThreadInitThunk [0x75EB7D59+25]\n\tRtlInitializeExceptionChain [0x77A4B79B+107]\n\tRtlClearBits [0x77A4B71F+191]\n\n", "trace": "  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\New folder\\python_selenium\\tests\\conftest.py\", line 64, in setup\n    driver.maximize_window()\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 990, in maximize_window\n    self.execute(command, params)\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1692691884363, "stop": 1692691890466}], "start": 1692691884363, "stop": 1692691890525}